services:
  zabbix-mariadb:
    image: mariadb:11.4.5-noble
    container_name: zabbix-mariadb
    restart: always
    env_file: ".env"
    volumes:
      - zabbix-mariadb-data:/var/lib/mysql
    networks:
      - zabbix-network

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.0-latest
    container_name: zabbix-server
    restart: always
    env_file: ".env"
    ports:
      - "${ZABBIX_SERVER_PORT}:10051"
    volumes:
      - zabbix-alertscript-data:/usr/lib/zabbix/alertscripts
    depends_on:
      - zabbix-mariadb
    networks:
      - zabbix-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
    container_name: zabbix-web
    restart: always
    env_file: ".env"
    ports:
      - "${ZABBIX_WEB_PORT}:8080"
    depends_on:
      - zabbix-mariadb
      - zabbix-server
    networks:
      - zabbix-network

  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-6.0-latest
    container_name: zabbix-agent
    restart: always
    env_file: ".env"
    privileged: true
    networks:
      - zabbix-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    env_file: ".env"
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - zabbix-network

networks:
  zabbix-network:
    driver: bridge

volumes:
  zabbix-mariadb-data:
  zabbix-alertscript-data:
  grafana-data:
